# Generated by Django 5.2.4 on 2025-07-26 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 14, 56, 39, 689767, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
