# Generated by Django 5.2.4 on 2025-07-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('once', 'One-time'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly')], default='weekly', max_length=10)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of integers (0=Mon ... 6=Sun). Used if schedule_type is weekly/biweekly.')),
                ('one_time_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='modules.module')),
            ],
        ),
    ]
