# Generated by Django 5.2.4 on 2025-07-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='module',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='module',
            name='location',
        ),
        migrations.RemoveField(
            model_name='module',
            name='start_time',
        ),
        migrations.AddField(
            model_name='lecture',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
